version: '2.0'
services:
  Airflow:
    image: puckel/docker-airflow
    ports:
    - "8080:8080"
    volumes:
    - ~/AirflowDemo:/usr/local/airflow/dags
  mongo:
    image: mongo
    ports:
    - "27017:27017"